### ISSUE TITLE
Duplicate chip

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [LTVA1/furnace#193]
The famicom w/ VRC7 is duplicated in the New Song menu
![image](https://github.com/LTVA1/furnace/assets/111107624/d0be4b7b-6250-4b83-868c-c86cb10425fb)

**Comment by LTVA1** [comment]
One of them seems to be in Deflemask-compatible section... I probably need to filter out exact duplicates from search results. Does tildearrow version also show two VRC7 Famicoms?

**Comment by Abdullah-Ajeebi** [comment]
No.

**Comment by LTVA1** [comment]
fixed

**Comment by Abdullah-Ajeebi** [comment]
Confirmed
