### ISSUE TITLE
Click on Game Boy wavetable channel when using ECxx effect

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [LTVA1/furnace#227]
Video: 

https://github.com/LTVA1/furnace/assets/111107624/e198e842-677c-405b-a7e9-7293b214bf60

**Comment by Abdullah-Ajeebi** [comment]
Module: 
[bassy.zip](https://github.com/LTVA1/furnace/files/15209847/bassy.zip)

**Comment by LTVA1** [comment]
This is an inherent property of Game Boy wavetable channel. You can't control its volume finely, you have only three volume levels, plus you are just cutting the note which means that volume immediately goes to zero.

I tried replacing `ECxx` with `FCxx` effects and making a volume macro with release stage where I try to use other three volume levels to fade it out more nicely, but it still sounds meh.
