### ISSUE TITLE
[YMF276-LLE] Per-channel oscilloscope doesn't work

### ISSUE THREAD

**Issue by freq-mod** [LTVA1/furnace#89]
https://github.com/LTVA1/furnace/assets/32672779/84bfce5a-f504-4847-a167-760535b316de - the clip shows the behaviour.

**Comment by LTVA1** [comment]
As is the case with other LLE cores iirc. In order to make it work I need to either modify the emulation code or make cycle-accurate accumulating code in the acquire() function

**Comment by LTVA1** [comment]
I decided to leave it like so (at least for now) because other LLE cores show the same behaviour. I think the reason is that tildearrow thought of them as of render-only cores that don't need any per-chan oscilloscope

**Comment by freq-mod** [comment]
YM3812-LLE per ch oscilloscope works, YMF262-LLE doesn't. So it's either oversight or actual design choice given YM3812-LLE can work realtime in consumer CPUs

**Comment by LTVA1** [comment]
Hm, I need to look at how YM2812-LLE does it

**Comment by freq-mod** [comment]
https://github.com/tildearrow/furnace/issues/1728

**Comment by LTVA1** [comment]
Yeah, I definitely need to look at it

**Comment by freq-mod** [comment]
YMF262-LLE per chan osc is implemented now

**Comment by LTVA1** [comment]
Yeah, updated this from upstream. Tomorrow, if I have time after DAVE stuff, I will try to make YMF276-LLE work too.

**Comment by LTVA1** [comment]
It finally works in YM3438 and YMF276 modes. Please check by yourself since I have tested only on one module. Oscilloscopes also should properly display signals in DualPCM mode too.
